### ISSUE TITLE
Cool package/naming

### ISSUE THREAD

**Issue by mlubin** [rdeits/ConditionalJuMP.jl#24]
Very cool that you've made this, it's something we've been thinking about for a long time. I have to ask you to put a disclaimer in the README that this package is not developed or maintained by the JuMP developers, since the name might suggest otherwise. When you're ready for the attention, we'd be happy to list it at http://www.juliaopt.org/packages/.

@JuliaOpt

**Comment by rdeits** [comment]
Sure, no problem! I'm on my phone now, but I'll do it as soon as I can.

**Comment by rdeits** [comment]
done!

**Comment by mlubin** [comment]
Thanks!
