### ISSUE TITLE
Try to avoid variable name conflicts with user variables

### ISSUE THREAD

**Issue by rdeits** [rdeits/ConditionalJuMP.jl#30]
As pointed out by @vtjeng, it's confusing to introduce new variables just called `y`, since that's likely to get confused for user variables (this doesn't affect model correctness, but can make the result of printing the model confusing). E.g.:

![screenshot from 2017-09-29 19-30-14](https://user-images.githubusercontent.com/591886/31092441-71ad6370-a77c-11e7-9689-64f4fd6135a9.png)

**Comment by vtjeng** [comment]
To add a bit of detail: in the printed output,
   + The `y` in the third-to-last line (with bounds `0 <= y <= 5`) refers to the variable that we specified using the `@variable` macro
   + The `y` in the second-to-last line (with bounds `1 <= y <= 6`) is the variable auto-generated by the `ConditionalJuMP` `@switch` macro.
